# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20161028_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=registration.models.min_birth_date),
        ),
    ]
