# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 18:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20161025_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationconfirm',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
