# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20161028_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unpack_ipv4=True)),
                ('added', models.DateTimeField(null=True)),
                ('requests_count', models.IntegerField(default=1)),
            ],
        ),
    ]
