# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20161025_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationconfirm',
            name='is_active',
        ),
    ]
