# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_user_birth_date'),
        ('registration', '0003_bannedip'),
    ]

    operations = [
    ]
