# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_merge_20161215_1058'),
        ('registration', '0004_merge_20161207_2127'),
        ('registration', '0005_user_avatar_background'),
    ]

    operations = [
    ]
