# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_merge_20161220_1923'),
        ('registration', '0004_merge_20161219_1212'),
    ]

    operations = [
    ]
