# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0002_auto_20161028_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('company_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.User')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', related_query_name='team', to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='TeamUserAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.User')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='companies.TeamUserAssignment', to='registration.User'),
        ),
    ]
