# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
