# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20161028_2141'),
        ('companies', '0004_auto_20161108_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='admin',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ruled_team', to='registration.User'),
            preserve_default=False,
        ),
    ]
