# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='homepage',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job',
            field=models.TextField(blank=True, null=True),
        ),
    ]
