# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20161025_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(through='event.EventUserAssignment', to='registration.User'),
        ),
        migrations.AlterField(
            model_name='eventuserassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.User'),
        ),
    ]
