# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20161103_2123'),
        ('event', '0004_auto_20161101_2217'),
    ]

    operations = [
    ]
