# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20161115_1035'),
        ('event', '0006_auto_20161114_2355'),
    ]

    operations = [
    ]
