# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20161028_2141'),
        ('event', '0009_remove_event_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='registration.User'),
            preserve_default=False,
        ),
    ]
