# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20161121_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventuserassignment',
            options={'ordering': ['-event__start_date']},
        ),
    ]
