# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='custom_value',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='location',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='place',
        ),
        migrations.AddField(
            model_name='choice',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='value',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
